apiVersion: v1
kind: Service
metadata:
  name: pgsql-dev-service
  namespace: pgsql-dev-ns
spec:
  type: NodePort
  selector:
    app: pgsql-dev
    environment: dev
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30543