apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-prod-certificate
  namespace: jenkins-prod-ns
spec:
  dnsNames:
    - jenkins-dkc.com
  secretName: jenkins-prod-certificate-selfsigned
  issuerRef:
    name: jenkins-prod-issuer