apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-dev-pvc
  namespace: pgsql-dev-ns
spec:
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-001