apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-002
  labels:
    storage: default
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv-002
    type: DirectoryOrCreate