apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-001
  labels:
    storage: default
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv-001
    type: DirectoryOrCreate